[2022-02-13 22:37:41,548] {processor.py:163} INFO - Started process (PID=5926) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:37:41,552] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:37:41,556] {logging_mixin.py:109} INFO - [2022-02-13 22:37:41,555] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:37:41,600] {logging_mixin.py:109} INFO - [2022-02-13 22:37:41,593] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:37:41,626] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:37:41,661] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.132 seconds
[2022-02-13 22:38:11,768] {processor.py:163} INFO - Started process (PID=5980) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:38:11,770] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:38:11,773] {logging_mixin.py:109} INFO - [2022-02-13 22:38:11,772] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:38:11,789] {logging_mixin.py:109} INFO - [2022-02-13 22:38:11,786] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:38:11,812] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:38:11,830] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.068 seconds
[2022-02-13 22:38:42,034] {processor.py:163} INFO - Started process (PID=6034) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:38:42,036] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:38:42,037] {logging_mixin.py:109} INFO - [2022-02-13 22:38:42,037] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:38:42,048] {logging_mixin.py:109} INFO - [2022-02-13 22:38:42,046] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:38:42,076] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:38:42,091] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.061 seconds
[2022-02-13 22:39:12,821] {processor.py:163} INFO - Started process (PID=6096) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:39:12,827] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:39:12,833] {logging_mixin.py:109} INFO - [2022-02-13 22:39:12,832] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:39:12,854] {logging_mixin.py:109} INFO - [2022-02-13 22:39:12,849] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:39:12,890] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:39:12,915] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.105 seconds
[2022-02-13 22:39:43,268] {processor.py:163} INFO - Started process (PID=6148) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:39:43,272] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:39:43,278] {logging_mixin.py:109} INFO - [2022-02-13 22:39:43,278] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:39:43,302] {logging_mixin.py:109} INFO - [2022-02-13 22:39:43,297] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:39:43,342] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:39:43,377] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.146 seconds
[2022-02-13 22:40:13,810] {processor.py:163} INFO - Started process (PID=6200) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:40:13,816] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:40:13,818] {logging_mixin.py:109} INFO - [2022-02-13 22:40:13,818] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:40:13,834] {logging_mixin.py:109} INFO - [2022-02-13 22:40:13,829] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:40:13,880] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:40:13,934] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.135 seconds
[2022-02-13 22:40:44,225] {processor.py:163} INFO - Started process (PID=6252) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:40:44,228] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:40:44,232] {logging_mixin.py:109} INFO - [2022-02-13 22:40:44,232] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:40:44,252] {logging_mixin.py:109} INFO - [2022-02-13 22:40:44,249] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:40:44,287] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:40:44,303] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.083 seconds
[2022-02-13 22:41:14,842] {processor.py:163} INFO - Started process (PID=6304) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:41:14,851] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:41:14,858] {logging_mixin.py:109} INFO - [2022-02-13 22:41:14,858] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:41:14,903] {logging_mixin.py:109} INFO - [2022-02-13 22:41:14,889] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:41:14,976] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:41:15,002] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.166 seconds
[2022-02-13 22:41:45,366] {processor.py:163} INFO - Started process (PID=6357) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:41:45,373] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:41:45,377] {logging_mixin.py:109} INFO - [2022-02-13 22:41:45,377] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:41:45,400] {logging_mixin.py:109} INFO - [2022-02-13 22:41:45,394] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:41:45,447] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:41:45,474] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.125 seconds
[2022-02-13 22:42:15,799] {processor.py:163} INFO - Started process (PID=6411) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:42:15,802] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:42:15,806] {logging_mixin.py:109} INFO - [2022-02-13 22:42:15,805] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:42:15,820] {logging_mixin.py:109} INFO - [2022-02-13 22:42:15,817] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:42:15,848] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:42:15,865] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.072 seconds
[2022-02-13 22:42:46,810] {processor.py:163} INFO - Started process (PID=6463) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:42:46,813] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:42:46,815] {logging_mixin.py:109} INFO - [2022-02-13 22:42:46,815] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:42:46,829] {logging_mixin.py:109} INFO - [2022-02-13 22:42:46,826] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:42:46,860] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:42:46,874] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.069 seconds
[2022-02-13 22:43:17,599] {processor.py:163} INFO - Started process (PID=6525) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:43:17,606] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:43:17,611] {logging_mixin.py:109} INFO - [2022-02-13 22:43:17,610] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:43:17,634] {logging_mixin.py:109} INFO - [2022-02-13 22:43:17,630] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:43:17,674] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:43:17,693] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.104 seconds
[2022-02-13 22:43:48,132] {processor.py:163} INFO - Started process (PID=6579) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:43:48,134] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:43:48,136] {logging_mixin.py:109} INFO - [2022-02-13 22:43:48,136] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:43:48,149] {logging_mixin.py:109} INFO - [2022-02-13 22:43:48,147] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:43:48,177] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:43:48,188] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.060 seconds
[2022-02-13 22:44:18,842] {processor.py:163} INFO - Started process (PID=6630) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:44:18,844] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:44:18,846] {logging_mixin.py:109} INFO - [2022-02-13 22:44:18,846] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:44:18,862] {logging_mixin.py:109} INFO - [2022-02-13 22:44:18,859] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:44:18,892] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:44:18,904] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.066 seconds
[2022-02-13 22:44:49,047] {processor.py:163} INFO - Started process (PID=6681) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:44:49,049] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:44:49,052] {logging_mixin.py:109} INFO - [2022-02-13 22:44:49,051] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:44:49,070] {logging_mixin.py:109} INFO - [2022-02-13 22:44:49,066] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:44:49,116] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:44:49,130] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.088 seconds
[2022-02-13 22:45:19,433] {processor.py:163} INFO - Started process (PID=6746) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:45:19,435] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:45:19,437] {logging_mixin.py:109} INFO - [2022-02-13 22:45:19,437] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:45:19,451] {logging_mixin.py:109} INFO - [2022-02-13 22:45:19,448] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:45:19,476] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:45:19,490] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.065 seconds
[2022-02-13 22:45:49,869] {processor.py:163} INFO - Started process (PID=6801) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:45:49,881] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:45:49,884] {logging_mixin.py:109} INFO - [2022-02-13 22:45:49,883] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:45:49,907] {logging_mixin.py:109} INFO - [2022-02-13 22:45:49,903] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:45:49,936] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:45:49,968] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.104 seconds
[2022-02-13 22:46:20,117] {processor.py:163} INFO - Started process (PID=6853) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:46:20,120] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:46:20,123] {logging_mixin.py:109} INFO - [2022-02-13 22:46:20,123] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:46:20,137] {logging_mixin.py:109} INFO - [2022-02-13 22:46:20,134] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:46:20,161] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:46:20,178] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.071 seconds
[2022-02-13 22:46:51,085] {processor.py:163} INFO - Started process (PID=6905) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:46:51,087] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:46:51,089] {logging_mixin.py:109} INFO - [2022-02-13 22:46:51,088] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:46:51,103] {logging_mixin.py:109} INFO - [2022-02-13 22:46:51,100] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:46:51,134] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:46:51,143] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.065 seconds
[2022-02-13 22:47:21,356] {processor.py:163} INFO - Started process (PID=6960) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:47:21,360] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:47:21,364] {logging_mixin.py:109} INFO - [2022-02-13 22:47:21,364] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:47:21,386] {logging_mixin.py:109} INFO - [2022-02-13 22:47:21,382] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:47:21,408] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:47:21,429] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.080 seconds
[2022-02-13 22:47:51,872] {processor.py:163} INFO - Started process (PID=7015) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:47:51,877] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:47:51,879] {logging_mixin.py:109} INFO - [2022-02-13 22:47:51,879] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:47:51,894] {logging_mixin.py:109} INFO - [2022-02-13 22:47:51,891] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:47:51,925] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:47:51,949] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.086 seconds
[2022-02-13 22:48:22,592] {processor.py:163} INFO - Started process (PID=7069) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:48:22,594] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:48:22,596] {logging_mixin.py:109} INFO - [2022-02-13 22:48:22,596] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:48:22,616] {logging_mixin.py:109} INFO - [2022-02-13 22:48:22,612] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:48:22,663] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:48:22,692] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.105 seconds
[2022-02-13 22:48:52,967] {processor.py:163} INFO - Started process (PID=7122) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:48:52,970] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:48:52,972] {logging_mixin.py:109} INFO - [2022-02-13 22:48:52,971] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:48:52,981] {logging_mixin.py:109} INFO - [2022-02-13 22:48:52,979] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:48:53,002] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:48:53,012] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.048 seconds
[2022-02-13 22:49:23,196] {processor.py:163} INFO - Started process (PID=7185) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:49:23,201] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:49:23,205] {logging_mixin.py:109} INFO - [2022-02-13 22:49:23,204] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:49:23,227] {logging_mixin.py:109} INFO - [2022-02-13 22:49:23,222] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:49:23,264] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:49:23,280] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.094 seconds
[2022-02-13 22:49:54,017] {processor.py:163} INFO - Started process (PID=7239) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:49:54,021] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:49:54,024] {logging_mixin.py:109} INFO - [2022-02-13 22:49:54,024] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:49:54,040] {logging_mixin.py:109} INFO - [2022-02-13 22:49:54,037] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:49:54,065] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:49:54,078] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.066 seconds
[2022-02-13 22:50:24,420] {processor.py:163} INFO - Started process (PID=7295) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:50:24,423] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:50:24,425] {logging_mixin.py:109} INFO - [2022-02-13 22:50:24,425] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:50:24,437] {logging_mixin.py:109} INFO - [2022-02-13 22:50:24,434] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:50:24,471] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:50:24,486] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.071 seconds
[2022-02-13 22:50:54,920] {processor.py:163} INFO - Started process (PID=7349) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:50:54,923] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:50:54,925] {logging_mixin.py:109} INFO - [2022-02-13 22:50:54,925] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:50:54,940] {logging_mixin.py:109} INFO - [2022-02-13 22:50:54,937] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:50:54,968] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:50:55,009] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.094 seconds
[2022-02-13 22:51:25,736] {processor.py:163} INFO - Started process (PID=7412) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:51:25,743] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:51:25,752] {logging_mixin.py:109} INFO - [2022-02-13 22:51:25,752] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:51:25,784] {logging_mixin.py:109} INFO - [2022-02-13 22:51:25,778] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:51:25,831] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:51:25,852] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.123 seconds
[2022-02-13 22:51:56,305] {processor.py:163} INFO - Started process (PID=7468) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:51:56,307] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:51:56,311] {logging_mixin.py:109} INFO - [2022-02-13 22:51:56,311] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:51:56,333] {logging_mixin.py:109} INFO - [2022-02-13 22:51:56,323] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:51:56,365] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:51:56,469] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.168 seconds
[2022-02-13 22:52:26,597] {processor.py:163} INFO - Started process (PID=7524) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:52:26,605] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:52:26,610] {logging_mixin.py:109} INFO - [2022-02-13 22:52:26,610] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:52:26,635] {logging_mixin.py:109} INFO - [2022-02-13 22:52:26,631] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:52:26,658] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:52:26,668] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.076 seconds
[2022-02-13 22:52:56,962] {processor.py:163} INFO - Started process (PID=7578) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:52:56,964] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:52:56,965] {logging_mixin.py:109} INFO - [2022-02-13 22:52:56,965] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:52:56,975] {logging_mixin.py:109} INFO - [2022-02-13 22:52:56,973] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:52:56,996] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:52:57,009] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.051 seconds
[2022-02-13 22:53:27,609] {processor.py:163} INFO - Started process (PID=7641) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:53:27,612] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:53:27,613] {logging_mixin.py:109} INFO - [2022-02-13 22:53:27,613] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:53:27,623] {logging_mixin.py:109} INFO - [2022-02-13 22:53:27,621] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:53:27,644] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:53:27,654] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.049 seconds
[2022-02-13 22:53:57,708] {processor.py:163} INFO - Started process (PID=7694) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:53:57,709] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:53:57,711] {logging_mixin.py:109} INFO - [2022-02-13 22:53:57,711] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:53:57,722] {logging_mixin.py:109} INFO - [2022-02-13 22:53:57,719] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:53:57,745] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:53:57,759] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.055 seconds
[2022-02-13 22:54:28,434] {processor.py:163} INFO - Started process (PID=7756) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:54:28,437] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:54:28,439] {logging_mixin.py:109} INFO - [2022-02-13 22:54:28,439] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:54:28,455] {logging_mixin.py:109} INFO - [2022-02-13 22:54:28,451] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:54:28,479] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:54:28,492] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.064 seconds
[2022-02-13 22:54:59,437] {processor.py:163} INFO - Started process (PID=7810) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:54:59,442] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:54:59,446] {logging_mixin.py:109} INFO - [2022-02-13 22:54:59,445] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:54:59,470] {logging_mixin.py:109} INFO - [2022-02-13 22:54:59,465] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:54:59,507] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:54:59,527] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.102 seconds
[2022-02-13 22:55:30,059] {processor.py:163} INFO - Started process (PID=7862) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:55:30,063] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:55:30,065] {logging_mixin.py:109} INFO - [2022-02-13 22:55:30,065] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:55:30,081] {logging_mixin.py:109} INFO - [2022-02-13 22:55:30,078] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:55:30,115] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:55:30,131] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.077 seconds
[2022-02-13 22:56:00,682] {processor.py:163} INFO - Started process (PID=7917) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:56:00,690] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:56:00,695] {logging_mixin.py:109} INFO - [2022-02-13 22:56:00,694] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:56:00,730] {logging_mixin.py:109} INFO - [2022-02-13 22:56:00,720] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:56:00,811] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:56:00,836] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.165 seconds
[2022-02-13 22:56:31,396] {processor.py:163} INFO - Started process (PID=7970) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:56:31,422] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:56:31,443] {logging_mixin.py:109} INFO - [2022-02-13 22:56:31,442] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:56:31,555] {logging_mixin.py:109} INFO - [2022-02-13 22:56:31,539] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:56:31,616] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:56:31,639] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.252 seconds
[2022-02-13 22:57:02,143] {processor.py:163} INFO - Started process (PID=8022) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:57:02,149] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:57:02,154] {logging_mixin.py:109} INFO - [2022-02-13 22:57:02,153] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:57:02,179] {logging_mixin.py:109} INFO - [2022-02-13 22:57:02,175] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:57:02,222] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:57:02,243] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.107 seconds
[2022-02-13 22:57:23,293] {processor.py:163} INFO - Started process (PID=8065) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:57:23,298] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:57:23,301] {logging_mixin.py:109} INFO - [2022-02-13 22:57:23,300] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:57:23,344] {logging_mixin.py:109} INFO - [2022-02-13 22:57:23,340] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:57:23,390] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:57:23,410] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.127 seconds
[2022-02-13 22:57:53,744] {processor.py:163} INFO - Started process (PID=8119) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:57:53,746] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:57:53,748] {logging_mixin.py:109} INFO - [2022-02-13 22:57:53,748] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:57:53,758] {logging_mixin.py:109} INFO - [2022-02-13 22:57:53,756] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:57:53,780] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:57:53,792] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.053 seconds
[2022-02-13 22:58:24,078] {processor.py:163} INFO - Started process (PID=8181) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:58:24,084] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:58:24,088] {logging_mixin.py:109} INFO - [2022-02-13 22:58:24,088] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:58:24,112] {logging_mixin.py:109} INFO - [2022-02-13 22:58:24,105] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:58:24,157] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:58:24,174] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.106 seconds
[2022-02-13 22:58:54,469] {processor.py:163} INFO - Started process (PID=8235) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:58:54,471] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:58:54,473] {logging_mixin.py:109} INFO - [2022-02-13 22:58:54,473] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:58:54,487] {logging_mixin.py:109} INFO - [2022-02-13 22:58:54,484] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:58:54,517] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:58:54,534] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.069 seconds
[2022-02-13 22:59:24,979] {processor.py:163} INFO - Started process (PID=8287) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:59:24,982] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 22:59:24,984] {logging_mixin.py:109} INFO - [2022-02-13 22:59:24,983] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:59:24,998] {logging_mixin.py:109} INFO - [2022-02-13 22:59:24,995] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 22:59:25,028] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 22:59:25,039] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.064 seconds
[2022-02-13 23:14:28,512] {processor.py:163} INFO - Started process (PID=38) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:14:28,516] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:14:28,521] {logging_mixin.py:109} INFO - [2022-02-13 23:14:28,518] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:14:28,566] {logging_mixin.py:109} INFO - [2022-02-13 23:14:28,555] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:14:28,645] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:14:28,669] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.180 seconds
[2022-02-13 23:14:59,339] {processor.py:163} INFO - Started process (PID=92) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:14:59,341] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:14:59,343] {logging_mixin.py:109} INFO - [2022-02-13 23:14:59,343] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:14:59,356] {logging_mixin.py:109} INFO - [2022-02-13 23:14:59,354] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:14:59,382] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:14:59,397] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.061 seconds
[2022-02-13 23:15:29,632] {processor.py:163} INFO - Started process (PID=146) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:15:29,634] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:15:29,636] {logging_mixin.py:109} INFO - [2022-02-13 23:15:29,636] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:15:29,669] {logging_mixin.py:109} INFO - [2022-02-13 23:15:29,662] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:15:29,694] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:15:29,708] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.079 seconds
[2022-02-13 23:16:00,493] {processor.py:163} INFO - Started process (PID=208) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:16:00,498] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:16:00,500] {logging_mixin.py:109} INFO - [2022-02-13 23:16:00,500] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:16:00,516] {logging_mixin.py:109} INFO - [2022-02-13 23:16:00,513] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:16:00,554] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:16:00,585] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.098 seconds
[2022-02-13 23:16:30,739] {processor.py:163} INFO - Started process (PID=262) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:16:30,742] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:16:30,744] {logging_mixin.py:109} INFO - [2022-02-13 23:16:30,744] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:16:30,759] {logging_mixin.py:109} INFO - [2022-02-13 23:16:30,756] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:16:30,789] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:16:30,807] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.073 seconds
[2022-02-13 23:17:01,426] {processor.py:163} INFO - Started process (PID=315) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:17:01,430] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:17:01,433] {logging_mixin.py:109} INFO - [2022-02-13 23:17:01,433] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:17:01,453] {logging_mixin.py:109} INFO - [2022-02-13 23:17:01,447] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:17:01,492] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:17:01,511] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.098 seconds
[2022-02-13 23:17:31,863] {processor.py:163} INFO - Started process (PID=368) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:17:31,870] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:17:31,871] {logging_mixin.py:109} INFO - [2022-02-13 23:17:31,871] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:17:31,886] {logging_mixin.py:109} INFO - [2022-02-13 23:17:31,882] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:17:31,913] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:17:31,927] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.068 seconds
[2022-02-13 23:18:02,349] {processor.py:163} INFO - Started process (PID=421) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:18:02,355] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:18:02,358] {logging_mixin.py:109} INFO - [2022-02-13 23:18:02,357] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:18:02,377] {logging_mixin.py:109} INFO - [2022-02-13 23:18:02,373] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:18:02,403] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:18:02,418] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.078 seconds
[2022-02-13 23:18:32,505] {processor.py:163} INFO - Started process (PID=484) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:18:32,508] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:18:32,510] {logging_mixin.py:109} INFO - [2022-02-13 23:18:32,510] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:18:32,522] {logging_mixin.py:109} INFO - [2022-02-13 23:18:32,519] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:18:32,547] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:18:32,559] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.058 seconds
[2022-02-13 23:19:02,978] {processor.py:163} INFO - Started process (PID=540) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:19:02,981] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:19:02,985] {logging_mixin.py:109} INFO - [2022-02-13 23:19:02,985] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:19:03,003] {logging_mixin.py:109} INFO - [2022-02-13 23:19:02,998] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:19:03,045] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:19:03,066] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.093 seconds
[2022-02-13 23:19:33,155] {processor.py:163} INFO - Started process (PID=594) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:19:33,158] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:19:33,159] {logging_mixin.py:109} INFO - [2022-02-13 23:19:33,159] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:19:33,170] {logging_mixin.py:109} INFO - [2022-02-13 23:19:33,168] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:19:33,190] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:19:33,201] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.051 seconds
[2022-02-13 23:20:03,476] {processor.py:163} INFO - Started process (PID=647) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:20:03,478] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:20:03,480] {logging_mixin.py:109} INFO - [2022-02-13 23:20:03,480] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:20:03,492] {logging_mixin.py:109} INFO - [2022-02-13 23:20:03,489] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:20:03,516] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:20:03,528] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.057 seconds
[2022-02-13 23:27:21,175] {processor.py:163} INFO - Started process (PID=40) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:27:21,181] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:27:21,184] {logging_mixin.py:109} INFO - [2022-02-13 23:27:21,184] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:27:21,201] {logging_mixin.py:109} INFO - [2022-02-13 23:27:21,195] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:27:21,236] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:27:21,253] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.087 seconds
[2022-02-13 23:27:52,049] {processor.py:163} INFO - Started process (PID=92) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:27:52,051] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:27:52,052] {logging_mixin.py:109} INFO - [2022-02-13 23:27:52,052] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:27:52,062] {logging_mixin.py:109} INFO - [2022-02-13 23:27:52,060] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:27:52,088] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:27:52,101] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.057 seconds
[2022-02-13 23:28:22,806] {processor.py:163} INFO - Started process (PID=154) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:28:22,808] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:28:22,810] {logging_mixin.py:109} INFO - [2022-02-13 23:28:22,810] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:28:22,822] {logging_mixin.py:109} INFO - [2022-02-13 23:28:22,820] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:28:22,845] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:28:22,862] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.059 seconds
[2022-02-13 23:28:53,762] {processor.py:163} INFO - Started process (PID=208) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:28:53,767] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:28:53,769] {logging_mixin.py:109} INFO - [2022-02-13 23:28:53,769] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:28:53,778] {logging_mixin.py:109} INFO - [2022-02-13 23:28:53,776] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:28:53,802] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:28:53,817] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.058 seconds
[2022-02-13 23:29:24,673] {processor.py:163} INFO - Started process (PID=271) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:29:24,675] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:29:24,677] {logging_mixin.py:109} INFO - [2022-02-13 23:29:24,677] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:29:24,687] {logging_mixin.py:109} INFO - [2022-02-13 23:29:24,685] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:29:24,705] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:29:24,714] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.046 seconds
[2022-02-13 23:29:55,443] {processor.py:163} INFO - Started process (PID=324) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:29:55,445] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:29:55,447] {logging_mixin.py:109} INFO - [2022-02-13 23:29:55,447] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:29:55,464] {logging_mixin.py:109} INFO - [2022-02-13 23:29:55,461] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:29:55,486] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:29:55,496] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.061 seconds
[2022-02-13 23:30:26,260] {processor.py:163} INFO - Started process (PID=388) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:30:26,262] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:30:26,264] {logging_mixin.py:109} INFO - [2022-02-13 23:30:26,264] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:30:26,274] {logging_mixin.py:109} INFO - [2022-02-13 23:30:26,272] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:30:26,297] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:30:26,307] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.051 seconds
[2022-02-13 23:30:56,930] {processor.py:163} INFO - Started process (PID=441) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:30:56,932] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:30:56,933] {logging_mixin.py:109} INFO - [2022-02-13 23:30:56,933] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:30:56,942] {logging_mixin.py:109} INFO - [2022-02-13 23:30:56,940] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:30:56,964] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:30:56,975] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.048 seconds
[2022-02-13 23:31:27,728] {processor.py:163} INFO - Started process (PID=503) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:31:27,731] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:31:27,732] {logging_mixin.py:109} INFO - [2022-02-13 23:31:27,732] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:31:27,743] {logging_mixin.py:109} INFO - [2022-02-13 23:31:27,741] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:31:27,763] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:31:27,778] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.055 seconds
[2022-02-13 23:31:58,491] {processor.py:163} INFO - Started process (PID=558) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:31:58,494] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:31:58,497] {logging_mixin.py:109} INFO - [2022-02-13 23:31:58,497] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:31:58,510] {logging_mixin.py:109} INFO - [2022-02-13 23:31:58,507] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:31:58,538] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:31:58,554] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.068 seconds
[2022-02-13 23:32:29,497] {processor.py:163} INFO - Started process (PID=612) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:32:29,501] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:32:29,503] {logging_mixin.py:109} INFO - [2022-02-13 23:32:29,503] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:32:29,524] {logging_mixin.py:109} INFO - [2022-02-13 23:32:29,519] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:32:29,557] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:32:29,573] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.082 seconds
[2022-02-13 23:32:59,677] {processor.py:163} INFO - Started process (PID=663) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:32:59,685] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:32:59,688] {logging_mixin.py:109} INFO - [2022-02-13 23:32:59,688] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:32:59,707] {logging_mixin.py:109} INFO - [2022-02-13 23:32:59,703] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:32:59,764] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:32:59,782] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.113 seconds
[2022-02-13 23:33:30,243] {processor.py:163} INFO - Started process (PID=729) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:33:30,246] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:33:30,247] {logging_mixin.py:109} INFO - [2022-02-13 23:33:30,247] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:33:30,256] {logging_mixin.py:109} INFO - [2022-02-13 23:33:30,254] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:33:30,281] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:33:30,295] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.055 seconds
[2022-02-13 23:34:00,653] {processor.py:163} INFO - Started process (PID=780) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:34:00,657] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:34:00,659] {logging_mixin.py:109} INFO - [2022-02-13 23:34:00,659] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:34:00,671] {logging_mixin.py:109} INFO - [2022-02-13 23:34:00,669] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:34:00,696] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:34:00,707] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.062 seconds
[2022-02-13 23:34:32,197] {processor.py:163} INFO - Started process (PID=835) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:34:32,201] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:34:32,205] {logging_mixin.py:109} INFO - [2022-02-13 23:34:32,204] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:34:32,267] {logging_mixin.py:109} INFO - [2022-02-13 23:34:32,248] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:34:32,536] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:34:32,684] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.494 seconds
[2022-02-13 23:35:03,571] {processor.py:163} INFO - Started process (PID=897) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:35:03,577] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:35:03,580] {logging_mixin.py:109} INFO - [2022-02-13 23:35:03,579] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:35:03,594] {logging_mixin.py:109} INFO - [2022-02-13 23:35:03,590] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:35:03,621] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:35:03,638] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.075 seconds
[2022-02-13 23:35:34,176] {processor.py:163} INFO - Started process (PID=949) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:35:34,178] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:35:34,179] {logging_mixin.py:109} INFO - [2022-02-13 23:35:34,179] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:35:34,200] {logging_mixin.py:109} INFO - [2022-02-13 23:35:34,196] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:35:34,231] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:35:34,243] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.073 seconds
[2022-02-13 23:36:04,868] {processor.py:163} INFO - Started process (PID=1001) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:36:04,871] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:36:04,872] {logging_mixin.py:109} INFO - [2022-02-13 23:36:04,872] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:36:04,886] {logging_mixin.py:109} INFO - [2022-02-13 23:36:04,882] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:36:04,912] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:36:04,928] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.069 seconds
[2022-02-13 23:36:35,551] {processor.py:163} INFO - Started process (PID=1063) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:36:35,555] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:36:35,557] {logging_mixin.py:109} INFO - [2022-02-13 23:36:35,557] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:36:35,578] {logging_mixin.py:109} INFO - [2022-02-13 23:36:35,573] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:36:35,612] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:36:35,629] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.083 seconds
[2022-02-13 23:37:05,689] {processor.py:163} INFO - Started process (PID=1119) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:37:05,692] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:37:05,694] {logging_mixin.py:109} INFO - [2022-02-13 23:37:05,694] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:37:05,705] {logging_mixin.py:109} INFO - [2022-02-13 23:37:05,702] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:37:05,729] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:37:05,742] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.057 seconds
[2022-02-13 23:37:36,148] {processor.py:163} INFO - Started process (PID=1172) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:37:36,150] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:37:36,151] {logging_mixin.py:109} INFO - [2022-02-13 23:37:36,151] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:37:36,161] {logging_mixin.py:109} INFO - [2022-02-13 23:37:36,159] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:37:36,191] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:37:36,213] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.069 seconds
[2022-02-13 23:38:06,405] {processor.py:163} INFO - Started process (PID=1226) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:38:06,408] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:38:06,410] {logging_mixin.py:109} INFO - [2022-02-13 23:38:06,410] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:38:06,425] {logging_mixin.py:109} INFO - [2022-02-13 23:38:06,420] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:38:06,447] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:38:06,460] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.062 seconds
[2022-02-13 23:38:37,358] {processor.py:163} INFO - Started process (PID=1290) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:38:37,361] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:38:37,362] {logging_mixin.py:109} INFO - [2022-02-13 23:38:37,362] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:38:37,373] {logging_mixin.py:109} INFO - [2022-02-13 23:38:37,371] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:38:37,395] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:38:37,405] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.052 seconds
[2022-02-13 23:39:08,105] {processor.py:163} INFO - Started process (PID=1342) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:39:08,108] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:39:08,109] {logging_mixin.py:109} INFO - [2022-02-13 23:39:08,109] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:39:08,118] {logging_mixin.py:109} INFO - [2022-02-13 23:39:08,116] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:39:08,138] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:39:08,148] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.051 seconds
[2022-02-13 23:39:39,033] {processor.py:163} INFO - Started process (PID=1395) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:39:39,035] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:39:39,037] {logging_mixin.py:109} INFO - [2022-02-13 23:39:39,037] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:39:39,048] {logging_mixin.py:109} INFO - [2022-02-13 23:39:39,045] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:39:39,068] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:39:39,079] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.051 seconds
[2022-02-13 23:40:09,877] {processor.py:163} INFO - Started process (PID=1460) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:40:09,879] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:40:09,880] {logging_mixin.py:109} INFO - [2022-02-13 23:40:09,880] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:40:09,890] {logging_mixin.py:109} INFO - [2022-02-13 23:40:09,888] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:40:09,910] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:40:09,922] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.049 seconds
[2022-02-13 23:40:40,745] {processor.py:163} INFO - Started process (PID=1513) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:40:40,747] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:40:40,749] {logging_mixin.py:109} INFO - [2022-02-13 23:40:40,748] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:40:40,758] {logging_mixin.py:109} INFO - [2022-02-13 23:40:40,756] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:40:40,778] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:40:40,787] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.046 seconds
[2022-02-13 23:41:11,675] {processor.py:163} INFO - Started process (PID=1578) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:41:11,677] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:41:11,679] {logging_mixin.py:109} INFO - [2022-02-13 23:41:11,679] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:41:11,689] {logging_mixin.py:109} INFO - [2022-02-13 23:41:11,686] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:41:11,714] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:41:11,729] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.059 seconds
[2022-02-13 23:41:41,911] {processor.py:163} INFO - Started process (PID=1630) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:41:41,913] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:41:41,914] {logging_mixin.py:109} INFO - [2022-02-13 23:41:41,914] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:41:41,925] {logging_mixin.py:109} INFO - [2022-02-13 23:41:41,923] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:41:41,945] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:41:41,954] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.046 seconds
[2022-02-13 23:42:12,544] {processor.py:163} INFO - Started process (PID=1692) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:42:12,545] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:42:12,547] {logging_mixin.py:109} INFO - [2022-02-13 23:42:12,547] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:42:12,557] {logging_mixin.py:109} INFO - [2022-02-13 23:42:12,554] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:42:12,578] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:42:12,590] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.049 seconds
[2022-02-13 23:42:42,914] {processor.py:163} INFO - Started process (PID=1745) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:42:42,916] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:42:42,918] {logging_mixin.py:109} INFO - [2022-02-13 23:42:42,918] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:42:42,929] {logging_mixin.py:109} INFO - [2022-02-13 23:42:42,927] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:42:42,962] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:42:42,981] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.071 seconds
[2022-02-13 23:43:13,203] {processor.py:163} INFO - Started process (PID=1796) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:43:13,206] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:43:13,208] {logging_mixin.py:109} INFO - [2022-02-13 23:43:13,208] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:43:13,221] {logging_mixin.py:109} INFO - [2022-02-13 23:43:13,218] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:43:13,245] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:43:13,255] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.056 seconds
[2022-02-13 23:43:43,635] {processor.py:163} INFO - Started process (PID=1856) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:43:43,639] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:43:43,641] {logging_mixin.py:109} INFO - [2022-02-13 23:43:43,641] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:43:43,655] {logging_mixin.py:109} INFO - [2022-02-13 23:43:43,652] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:43:43,682] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:43:43,803] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.171 seconds
[2022-02-13 23:44:13,920] {processor.py:163} INFO - Started process (PID=1910) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:44:13,923] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:44:13,925] {logging_mixin.py:109} INFO - [2022-02-13 23:44:13,925] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:44:13,947] {logging_mixin.py:109} INFO - [2022-02-13 23:44:13,941] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:44:14,118] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:44:14,153] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.241 seconds
[2022-02-13 23:44:44,892] {processor.py:163} INFO - Started process (PID=1963) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:44:44,894] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:44:44,896] {logging_mixin.py:109} INFO - [2022-02-13 23:44:44,896] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:44:44,909] {logging_mixin.py:109} INFO - [2022-02-13 23:44:44,904] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:44:44,934] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:44:44,950] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.062 seconds
[2022-02-13 23:45:15,706] {processor.py:163} INFO - Started process (PID=2025) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:45:15,711] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:45:15,713] {logging_mixin.py:109} INFO - [2022-02-13 23:45:15,713] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:45:15,727] {logging_mixin.py:109} INFO - [2022-02-13 23:45:15,726] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:45:15,744] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:45:15,754] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.053 seconds
[2022-02-13 23:45:46,405] {processor.py:163} INFO - Started process (PID=2076) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:45:46,407] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:45:46,409] {logging_mixin.py:109} INFO - [2022-02-13 23:45:46,409] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:45:46,421] {logging_mixin.py:109} INFO - [2022-02-13 23:45:46,418] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:45:46,447] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:45:46,462] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.061 seconds
[2022-02-13 23:46:17,321] {processor.py:163} INFO - Started process (PID=2139) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:46:17,323] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:46:17,324] {logging_mixin.py:109} INFO - [2022-02-13 23:46:17,324] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:46:17,334] {logging_mixin.py:109} INFO - [2022-02-13 23:46:17,331] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:46:17,357] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:46:17,366] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.049 seconds
[2022-02-13 23:46:47,857] {processor.py:163} INFO - Started process (PID=2193) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:46:47,859] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:46:47,860] {logging_mixin.py:109} INFO - [2022-02-13 23:46:47,860] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:46:47,867] {logging_mixin.py:109} INFO - [2022-02-13 23:46:47,866] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:46:47,888] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:46:47,898] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.044 seconds
[2022-02-13 23:47:18,630] {processor.py:163} INFO - Started process (PID=2254) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:47:18,632] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:47:18,634] {logging_mixin.py:109} INFO - [2022-02-13 23:47:18,633] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:47:18,643] {logging_mixin.py:109} INFO - [2022-02-13 23:47:18,641] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:47:18,661] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:47:18,672] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.045 seconds
[2022-02-13 23:47:49,277] {processor.py:163} INFO - Started process (PID=2308) to work on /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:47:49,284] {processor.py:642} INFO - Processing file /opt/airflow/dags/dbt-airflow.py for tasks to queue
[2022-02-13 23:47:49,287] {logging_mixin.py:109} INFO - [2022-02-13 23:47:49,286] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:47:49,307] {logging_mixin.py:109} INFO - [2022-02-13 23:47:49,302] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dbt-airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt-airflow.py", line 2, in <module>
    from airflow_dbt.operators.dbt_operator import (
ModuleNotFoundError: No module named 'airflow_dbt'
[2022-02-13 23:47:49,337] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt-airflow.py
[2022-02-13 23:47:49,355] {processor.py:171} INFO - Processing /opt/airflow/dags/dbt-airflow.py took 0.085 seconds
