[2022-02-15 02:29:17,150] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.test.my_new_project.fct_orders manual__2022-02-15T02:27:57.149490+00:00 [queued]>
[2022-02-15 02:29:17,178] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_training_bytecode.test.my_new_project.fct_orders manual__2022-02-15T02:27:57.149490+00:00 [queued]>
[2022-02-15 02:29:17,180] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 02:29:17,181] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-15 02:29:17,182] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 02:29:17,212] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): test.my_new_project.fct_orders> on 2022-02-15 02:27:57.149490+00:00
[2022-02-15 02:29:17,222] {standard_task_runner.py:52} INFO - Started process 927 to run task
[2022-02-15 02:29:17,238] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_training_bytecode', 'test.my_new_project.fct_orders', 'manual__2022-02-15T02:27:57.149490+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dbt-***.py', '--cfg-path', '/tmp/tmp9j0jjdpm', '--error-file', '/tmp/tmpp3al5erk']
[2022-02-15 02:29:17,240] {standard_task_runner.py:77} INFO - Job 78: Subtask test.my_new_project.fct_orders
[2022-02-15 02:29:17,378] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_training_bytecode.test.my_new_project.fct_orders manual__2022-02-15T02:27:57.149490+00:00 [running]> on host de7a240d0d46
[2022-02-15 02:29:17,506] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bytecode
AIRFLOW_CTX_DAG_ID=dbt_training_bytecode
AIRFLOW_CTX_TASK_ID=test.my_new_project.fct_orders
AIRFLOW_CTX_EXECUTION_DATE=2022-02-15T02:27:57.149490+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-15T02:27:57.149490+00:00
[2022-02-15 02:29:17,511] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-15 02:29:17,514] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            dbt --no-write-json test --target dev --models fct_orders             --profiles-dir /opt/***/dbt/dbt-training-bytecode-1 --project-dir /opt/***/dbt/dbt-training-bytecode-1\n            ']
[2022-02-15 02:29:17,538] {subprocess.py:85} INFO - Output:
[2022-02-15 02:29:25,120] {subprocess.py:89} INFO - 02:29:25  Running with dbt=1.0.1
[2022-02-15 02:29:25,504] {subprocess.py:89} INFO - 02:29:25  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2022-02-15 02:29:25,506] {subprocess.py:89} INFO - There are 2 unused configuration paths:
[2022-02-15 02:29:25,507] {subprocess.py:89} INFO - - models.jaffle_shop.marts.core
[2022-02-15 02:29:25,508] {subprocess.py:89} INFO - - models.jaffle_shop.staging
[2022-02-15 02:29:25,509] {subprocess.py:89} INFO - 
[2022-02-15 02:29:25,555] {subprocess.py:89} INFO - 02:29:25  Found 7 models, 11 tests, 0 snapshots, 0 analyses, 367 macros, 0 operations, 1 seed file, 3 sources, 0 exposures, 0 metrics
[2022-02-15 02:29:25,561] {subprocess.py:89} INFO - 02:29:25
[2022-02-15 02:29:25,566] {subprocess.py:89} INFO - 02:29:25  [WARNING]: Nothing to do. Try checking your model configs and model specification args
[2022-02-15 02:29:26,235] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-15 02:29:26,295] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dbt_training_bytecode, task_id=test.my_new_project.fct_orders, execution_date=20220215T022757, start_date=20220215T022917, end_date=20220215T022926
[2022-02-15 02:29:26,370] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-15 02:29:26,487] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
